server:
  port: ${SERVER_PORT}
  servlet:
    context-path: '/sangiorgio/'

spring:
  application:
    name: san-giorgio-api
    
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRE_URL}/sangiorgio
    username: ${POSTGRE_USERNAME}
    password: ${POSTGRE_PASSWORD}
  
  jpa:
    show-sql: true
    database: POSTGRESQL
    hibernate:
      ddl-auto: update

# application-mock-sqs.yaml
aws:
  sqs:
    region: us-east-1
    access-key: fake-access-key
    secret-key: fake-secret-key
    queue-urls:
      partial: http://localhost:4566/000000000000/partial-payments
      total: http://localhost:4566/000000000000/total-payments
      excess: http://localhost:4566/000000000000/excess-payments

#aws:
# sqs:
#    enabled: false
#    region: your-region
#    access-key: your-access-key
#    secret-key: your-secret-key
#    queue-urls:
#      partial: https://sqs.your-region.amazonaws.com/your-account-id/partial-payments
#      total: https://sqs.your-region.amazonaws.com/your-account-id/total-payments
#      excess: https://sqs.your-region.amazonaws.com/your-account-id/excess-payments

